Fix lw microwave asset version (#178)
## Summary

Fixes the microwave asset to the version we used to record our dataset
uploaded to
[hf](https://huggingface.co/datasets/nvidia/Arena-GR1-Manipulation-Task/tree/main).
The declaration "microwave" only pulls a random microwave available and
broke our replay as that microwave's joint count changed:

```
560, in write_joint_position_to_sim
    self._data.joint_pos[env_ids, joint_ids] = position
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape mismatch: value tensor of shape [2] cannot be broadcast to indexing result of shape [1, 4]
```